console.error("test error")
console.error("HARP!")
console.log("welcome!")
console.warn("you are not allowed to do that")
console.log("I would be a logger.")
console.error("still trying!")
console.error("make a change"!)
console.error("NO!")
console.warn("take your card and try again!")
console.log("Take your money")
